sylius_resource:
    resources:
        monsieurbiz_cms_page.page:
            classes:
                controller: MonsieurBiz\SyliusCmsPagePlugin\Controller\PageController
                model: MonsieurBiz\SyliusCmsPagePlugin\Entity\Page
                interface: MonsieurBiz\SyliusCmsPagePlugin\Entity\PageInterface
                form: MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageType
                repository: MonsieurBiz\SyliusCmsPagePlugin\Repository\PageRepository
            translation:
                classes:
                    model: MonsieurBiz\SyliusCmsPagePlugin\Entity\PageTranslation
                    interface: MonsieurBiz\SyliusCmsPagePlugin\Entity\PageTranslationInterface
